FROM openjdk:11-slim as build

LABEL authors="Elliot Lee"

ARG JAR_FILE

COPY ${JAR_FILE} app.jar

RUN mkdir -p target/dependancy && (cd target/dependency; jar -xf /app.jar)

FROM openjdk:11-slim

VOLUME /tmp

ARG DEPENDENCY=/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java", "-cp", "app:app/lib/*", "com.elliotlee.license.LicenseServiceApplication"]